-- AlterTable
ALTER TABLE "Phase" ADD COLUMN IF NOT EXISTS "submissionDeadlineAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "PhaseTrack" ADD COLUMN IF NOT EXISTS "submittedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "PhaseTrack" ADD COLUMN IF NOT EXISTS "lateSubmission" BOOLEAN NOT NULL DEFAULT false;
